name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "WASM_TAG=index-v0-1-0" >> $GITHUB_ENV
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: beta
          components: clippy
      - name: Run tests with cucumber
        run: cargo test -p template-state --test template-state-test
      - name: Run clippy
        run: cargo clippy -- -D clippy::expect_used -D clippy::panic  -D clippy::unwrap_used
      - name: Build project
        run: |
          mkdir artifact
          RUN apt update && apt install -y pkg-config ca-certificates libsasl2-dev libssl-dev
          RUN cargo install wasm-pack
          cargo build --locked --release --bin template-server
          cp ./target/release/template-server ./artifact/template-server
          wasm-pack build ./client --target web --out-dir ./artifact/web/template/ --out-name index-$WASM_TAG
          cp ./server/templates ./artifact/templates
      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-binary
          path: artifact/
          if-no-files-found: error